import { Lock, LogOut } from 'lucide-react';
import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import api, { errorMessage } from '../api/client.js';
import { useAuth } from '../context/AuthContext.jsx';

export default function SettingsPage() {
  const { user, logout } = useAuth(); const navigate = useNavigate(); const [form, setForm] = useState({ currentPassword: '', newPassword: '', confirm: '' }); const [status, setStatus] = useState(''); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  async function changePassword(e) { e.preventDefault(); setError(''); setStatus(''); if (form.newPassword !== form.confirm) { setError('New password and confirmation do not match.'); return; } setBusy(true); try { const { data } = await api.patch('/auth/password', { currentPassword: form.currentPassword, newPassword: form.newPassword }); setStatus(data.message); setForm({ currentPassword: '', newPassword: '', confirm: '' }); } catch (err) { setError(errorMessage(err)); } finally { setBusy(false); } }
  function signOut() { logout(); navigate('/login'); }
  return <div className="page settings-page"><div className="page-title"><h1>Settings</h1><p>Manage account security and session.</p></div><section className="surface settings-card"><h2>Account</h2><div className="account-line"><span>Email</span><strong>{user.email}</strong></div><div className="account-line"><span>Username</span><strong>@{user.username}</strong></div></section><form className="surface settings-card" onSubmit={changePassword}><div className="settings-heading"><Lock size={20}/><div><h2>Change password</h2><p>Use at least 8 characters.</p></div></div><label>Current password<input type="password" value={form.currentPassword} onChange={(e) => setForm({ ...form, currentPassword: e.target.value })} required/></label><label>New password<input type="password" minLength={8} value={form.newPassword} onChange={(e) => setForm({ ...form, newPassword: e.target.value })} required/></label><label>Confirm new password<input type="password" minLength={8} value={form.confirm} onChange={(e) => setForm({ ...form, confirm: e.target.value })} required/></label>{error && <div className="form-error">{error}</div>}{status && <div className="form-success">{status}</div>}<button className="primary-btn" disabled={busy}>{busy ? 'Updating...' : 'Update password'}</button></form><section className="surface settings-card"><button className="logout-wide" onClick={signOut}><LogOut size={18}/> Sign out of SocialSphere</button></section></div>;
}
